### ISSUE TITLE
QR code corresponding to a PDF course 

### ISSUE THREAD

**Issue by kladier** [kladier/miniprojet-android#12]
- [ ] détecter un QR code

- [ ] associer le résultat texte du QR code à un cours PDF

- [ ] afficher le cours PDF

**Comment by NotBad4U** [comment]
When I try to start the ScanQRCodeActivity I got this stacktrace :

```
03-13 23:53:10.660 12372-12372/univ.pr.nj.keewitz E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: univ.pr.nj.keewitz, PID: 12372
                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{univ.pr.nj.keewitz/univ.pr.nj.keewitz.ScanQRCodeActivity}: android.os.FileUriExposedException: file:///storage/emulated/0/Pic.jpg exposed beyond app through ClipData.Item.getUri()
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046)
                                                                        at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                        at android.os.Looper.loop(Looper.java:164)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6809)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                     Caused by: android.os.FileUriExposedException: file:///storage/emulated/0/Pic.jpg exposed beyond app through ClipData.Item.getUri()
                                                                        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
                                                                        at android.net.Uri.checkFileUriExposed(Uri.java:2348)
                                                                        at android.content.ClipData.prepareToLeaveProcess(ClipData.java:941)
                                                                        at android.content.Intent.prepareToLeaveProcess(Intent.java:9735)
                                                                        at android.content.Intent.prepareToLeaveProcess(Intent.java:9720)
                                                                        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1795)
                                                                        at android.app.Activity.startActivityForResult(Activity.java:4495)
                                                                        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
                                                                        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
                                                                        at android.app.Activity.startActivityForResult(Activity.java:4453)
                                                                        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:720)
                                                                        at univ.pr.nj.keewitz.ScanQRCodeActivity.takePhoto(ScanQRCodeActivity.java:52)
                                                                        at univ.pr.nj.keewitz.ScanQRCodeActivity.onCreate(ScanQRCodeActivity.java:36)
                                                                        at android.app.Activity.performCreate(Activity.java:6998)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1230)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046) 
                                                                        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                        at android.os.Looper.loop(Looper.java:164) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6809) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

The problem seems to come from this `Pic.jpg`.  Is there a file missing on my config (master  # e38bb55) ?

**Comment by kladier** [comment]
My bad je rectifierais en même temps que la finition de cette issue
